tests corr

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -33,11 +33,14 @@ jobs:
         uses: actions/setup-go@v4
         with:
           go-version: 1.20.3
-      - run: go test ./...
-             if [ $? -ne 0 ]; then
-              echo "Some tests failed"
-              exit 1
-             fi
+
+      - name: Execute tests
+        run: |
+          go test ./...
+          if [ $? -ne 0 ]; then
+            echo "Some tests failed"
+            exit 1
+          fi
       
       - name: login to dockerhub
         uses: docker/login-action@v2
